##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [2]:
arr = np.array([1,2,3,4])
print(arr * 5)     # Multiply every element by 5

[ 5 10 15 20]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [6]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([10,20,30])     # Shape (3,)

print(A + B)

[[11 22 33]
 [14 25 36]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [7]:
arr = np.array([4, 8, 15, 16, 23, 42])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Sum: 108
Mean: 18.0
Min: 4
Max: 42
Standard Deviation: 12.315302134607444
Variance: 151.66666666666666


You can also do the axis based operations row-Wise and Colum-wise

In [8]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("Sum of all:", np.sum(data))
print("Row-wise sum:", np.sum(data, axis=1))   # across columns
print("Column-wise sum:", np.sum(data, axis=0)) # across rows

print("Row-wise mean:", np.mean(data, axis=1))
print("Column-wise mean:", np.mean(data, axis=0))


Sum of all: 45
Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]
Row-wise mean: [2. 5. 8.]
Column-wise mean: [4. 5. 6.]
