##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [22]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)   # (2,3) → 2 rows, 3 cols
print("Dimensions:", arr.ndim)  # 2D array
print("Size:", arr.size)     # Total number of elements
print("Data type:", arr.dtype) # int64 / float64

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [24]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # 10
print(arr[-1])  # 50

10
50


Now lets see the 2D indexing aswell

In [25]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr[0] #only rows indexing

array([1, 2, 3])

In [34]:
arr[1,1] #2d indexing

np.int64(5)

Now we can also do the slicing lets see the **slicing in 1D**

In [35]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[2:8])     # [2 3 4 5 6 7]
print(arr[::2])     # Every 2nd element [0 2 4 6 8]
print(arr[::-1])    # Reverse array [9 8 7 ... 0]

[2 3 4 5 6 7]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


1D slicing was really easy now lets see the **slicing in 2D**

In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2, 1:3])
# Rows 0–1 and Cols 1–2 → [[2 3],[5 6]]

[[2 3]
 [5 6]]


There is one more thing known as **Boolean indexing**

In [37]:
arr = np.array([5, 10, 15, 20, 25])
print(arr > 12)        # [False False  True  True  True]
print(arr[arr > 12])   # [15 20 25]

[False False  True  True  True]
[15 20 25]


In [38]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [42]:
arr = np.arange(12)  # [0..11]
reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [43]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.flatten())   # [1 2 3 4 5 6]

[1 2 3 4 5 6]
